import { Audio, type CalculateMetadataFunction, staticFile } from "remotion";

import { SceneSeries } from "../components/SceneSeries";
import { TRANSITION_FRAMES } from "../course-trailer/pacing";
import { DURATION, SCENE_ORDER, TRANSITION, sceneFrames, type SceneId } from "./pacing";
import { ClosingScene } from "./scenes/ClosingScene";
import { HookScene } from "./scenes/HookScene";
import { CoursesScene, DevelopmentScene } from "./scenes/OfferScenes";
import { SiteTourScene } from "./scenes/SiteTourScene";
import type { Recording } from "./shots";

if (TRANSITION !== TRANSITION_FRAMES) {
  throw new Error("social-trailer/pacing.ts TRANSITION must match TRANSITION_FRAMES");
}

export type SocialTrailerProps = { recording: Recording | null };

/** Generated by scripts (see video/README.md); git-ignored. */
const RECORDING = "social-trailer/recording.json";
const SOUNDTRACK = "social-trailer/audio.wav";

/** Loads what `pnpm record` filmed, so the tour scene knows its clips. */
export const calculateSocialMetadata: CalculateMetadataFunction<SocialTrailerProps> = async ({ props }) => {
  const response = await fetch(staticFile(RECORDING));
  if (!response.ok) {
    throw new Error(`No public/${RECORDING}: run \`pnpm record\` (with the site running) first`);
  }
  return { durationInFrames: DURATION, props: { ...props, recording: (await response.json()) as Recording } };
};

/**
 * A 30 s announcement for social media: the redesigned site, filmed; custom
 * software development; the course areas; then the URL. Cut to the beat of
 * a soundtrack generated by `pnpm audio`.
 */
export function SocialTrailer({ recording }: SocialTrailerProps) {
  if (!recording) throw new Error("calculateSocialMetadata didn't load the recording");

  const scenes: Record<SceneId, React.ReactNode> = {
    hook: <HookScene />,
    tour: <SiteTourScene recording={recording} />,
    development: <DevelopmentScene />,
    courses: <CoursesScene />,
    closing: <ClosingScene />,
  };

  return (
    <>
      <SceneSeries scenes={SCENE_ORDER.map((id) => ({ frames: sceneFrames(id), content: scenes[id] }))} />
      <Audio src={staticFile(SOUNDTRACK)} />
    </>
  );
}
